"""Curated syllabi for JEE, NEET, NDA, Boards (CBSE Class 12)."""

JEE_SYLLABUS = {
    "Physics": [
        {"name": "Kinematics", "priority_weight": 3},
        {"name": "Laws of Motion", "priority_weight": 3},
        {"name": "Work, Power & Energy", "priority_weight": 3},
        {"name": "Rotational Motion", "priority_weight": 4},
        {"name": "Gravitation", "priority_weight": 2},
        {"name": "Properties of Solids & Liquids", "priority_weight": 2},
        {"name": "Thermodynamics", "priority_weight": 4},
        {"name": "Kinetic Theory of Gases", "priority_weight": 2},
        {"name": "Oscillations & Waves", "priority_weight": 4},
        {"name": "Ray Optics", "priority_weight": 3},
        {"name": "Wave Optics", "priority_weight": 3},
        {"name": "Electrostatics", "priority_weight": 5},
        {"name": "Current Electricity", "priority_weight": 5},
        {"name": "Magnetic Effects of Current & Magnetism", "priority_weight": 4},
        {"name": "Electromagnetic Induction & AC", "priority_weight": 4},
        {"name": "Electromagnetic Waves", "priority_weight": 2},
        {"name": "Dual Nature of Matter & Radiation", "priority_weight": 3},
        {"name": "Atoms & Nuclei", "priority_weight": 3},
        {"name": "Semiconductor Electronics", "priority_weight": 3},
    ],
    "Chemistry": [
        {"name": "Some Basic Concepts of Chemistry (Mole)", "priority_weight": 4},
        {"name": "Atomic Structure", "priority_weight": 3},
        {"name": "Chemical Bonding & Molecular Structure", "priority_weight": 5},
        {"name": "States of Matter (Gases & Liquids)", "priority_weight": 2},
        {"name": "Thermodynamics & Thermochemistry", "priority_weight": 4},
        {"name": "Solutions", "priority_weight": 3},
        {"name": "Equilibrium (Ionic & Chemical)", "priority_weight": 4},
        {"name": "Redox & Electrochemistry", "priority_weight": 4},
        {"name": "Chemical Kinetics", "priority_weight": 3},
        {"name": "Surface Chemistry", "priority_weight": 2},
        {"name": "Periodic Table & Periodicity", "priority_weight": 3},
        {"name": "s-Block Elements", "priority_weight": 2},
        {"name": "p-Block Elements", "priority_weight": 4},
        {"name": "d & f Block Elements", "priority_weight": 3},
        {"name": "Coordination Compounds", "priority_weight": 4},
        {"name": "General Organic Chemistry (GOC)", "priority_weight": 5},
        {"name": "Hydrocarbons", "priority_weight": 3},
        {"name": "Haloalkanes & Haloarenes", "priority_weight": 3},
        {"name": "Alcohols, Phenols & Ethers", "priority_weight": 3},
        {"name": "Aldehydes, Ketones & Carboxylic Acids", "priority_weight": 4},
        {"name": "Amines & Diazonium Salts", "priority_weight": 3},
        {"name": "Biomolecules & Polymers", "priority_weight": 2},
    ],
    "Mathematics": [
        {"name": "Sets, Relations & Functions", "priority_weight": 3},
        {"name": "Complex Numbers", "priority_weight": 3},
        {"name": "Quadratic Equations", "priority_weight": 3},
        {"name": "Matrices & Determinants", "priority_weight": 4},
        {"name": "Permutations & Combinations", "priority_weight": 3},
        {"name": "Binomial Theorem", "priority_weight": 3},
        {"name": "Sequences & Series", "priority_weight": 3},
        {"name": "Limits, Continuity & Differentiability", "priority_weight": 5},
        {"name": "Differentiation & Applications of Derivatives", "priority_weight": 5},
        {"name": "Integrals & Applications", "priority_weight": 5},
        {"name": "Differential Equations", "priority_weight": 3},
        {"name": "Straight Lines", "priority_weight": 3},
        {"name": "Circles", "priority_weight": 3},
        {"name": "Conic Sections (Parabola, Ellipse, Hyperbola)", "priority_weight": 4},
        {"name": "Three Dimensional Geometry", "priority_weight": 4},
        {"name": "Vector Algebra", "priority_weight": 4},
        {"name": "Probability", "priority_weight": 4},
        {"name": "Statistics", "priority_weight": 2},
        {"name": "Trigonometric Functions & Equations", "priority_weight": 3},
        {"name": "Inverse Trigonometric Functions", "priority_weight": 2},
        {"name": "Mathematical Reasoning", "priority_weight": 1},
    ],
}

NEET_SYLLABUS = {
    "Physics": [
        {"name": "Physical World & Measurement", "priority_weight": 1},
        {"name": "Kinematics", "priority_weight": 3},
        {"name": "Laws of Motion", "priority_weight": 3},
        {"name": "Work, Energy & Power", "priority_weight": 3},
        {"name": "System of Particles & Rotational Motion", "priority_weight": 3},
        {"name": "Gravitation", "priority_weight": 2},
        {"name": "Properties of Bulk Matter", "priority_weight": 2},
        {"name": "Thermodynamics", "priority_weight": 4},
        {"name": "Behaviour of Perfect Gas & Kinetic Theory", "priority_weight": 2},
        {"name": "Oscillations & Waves", "priority_weight": 3},
        {"name": "Electrostatics", "priority_weight": 4},
        {"name": "Current Electricity", "priority_weight": 4},
        {"name": "Magnetic Effects of Current & Magnetism", "priority_weight": 3},
        {"name": "Electromagnetic Induction & AC", "priority_weight": 3},
        {"name": "Electromagnetic Waves", "priority_weight": 2},
        {"name": "Optics (Ray + Wave)", "priority_weight": 4},
        {"name": "Dual Nature of Matter & Radiation", "priority_weight": 3},
        {"name": "Atoms & Nuclei", "priority_weight": 3},
        {"name": "Electronic Devices (Semiconductors)", "priority_weight": 3},
    ],
    "Chemistry": [
        {"name": "Some Basic Concepts of Chemistry", "priority_weight": 3},
        {"name": "Structure of Atom", "priority_weight": 3},
        {"name": "Classification of Elements & Periodicity", "priority_weight": 2},
        {"name": "Chemical Bonding & Molecular Structure", "priority_weight": 4},
        {"name": "States of Matter", "priority_weight": 2},
        {"name": "Thermodynamics", "priority_weight": 3},
        {"name": "Equilibrium", "priority_weight": 4},
        {"name": "Redox Reactions", "priority_weight": 2},
        {"name": "Hydrogen", "priority_weight": 1},
        {"name": "s-Block Elements", "priority_weight": 2},
        {"name": "p-Block Elements", "priority_weight": 4},
        {"name": "d & f-Block Elements", "priority_weight": 3},
        {"name": "Coordination Compounds", "priority_weight": 4},
        {"name": "Solid State", "priority_weight": 3},
        {"name": "Solutions", "priority_weight": 3},
        {"name": "Electrochemistry", "priority_weight": 3},
        {"name": "Chemical Kinetics", "priority_weight": 3},
        {"name": "Surface Chemistry", "priority_weight": 2},
        {"name": "General Organic Chemistry (GOC)", "priority_weight": 4},
        {"name": "Hydrocarbons", "priority_weight": 3},
        {"name": "Haloalkanes & Haloarenes", "priority_weight": 3},
        {"name": "Alcohols, Phenols & Ethers", "priority_weight": 3},
        {"name": "Aldehydes, Ketones & Carboxylic Acids", "priority_weight": 3},
        {"name": "Amines", "priority_weight": 3},
        {"name": "Biomolecules", "priority_weight": 3},
        {"name": "Polymers", "priority_weight": 1},
        {"name": "Chemistry in Everyday Life", "priority_weight": 1},
    ],
    "Botany": [
        {"name": "Diversity in Living World", "priority_weight": 3},
        {"name": "Plant Kingdom", "priority_weight": 3},
        {"name": "Morphology of Flowering Plants", "priority_weight": 3},
        {"name": "Anatomy of Flowering Plants", "priority_weight": 2},
        {"name": "Cell — Structure & Function", "priority_weight": 4},
        {"name": "Cell Cycle & Cell Division", "priority_weight": 3},
        {"name": "Transport in Plants", "priority_weight": 2},
        {"name": "Mineral Nutrition", "priority_weight": 2},
        {"name": "Photosynthesis", "priority_weight": 4},
        {"name": "Respiration in Plants", "priority_weight": 3},
        {"name": "Plant Growth & Development", "priority_weight": 3},
        {"name": "Reproduction in Flowering Plants", "priority_weight": 5},
        {"name": "Principles of Inheritance & Variation", "priority_weight": 5},
        {"name": "Molecular Basis of Inheritance", "priority_weight": 5},
        {"name": "Evolution", "priority_weight": 3},
        {"name": "Strategies for Enhancement in Food Production", "priority_weight": 2},
        {"name": "Microbes in Human Welfare", "priority_weight": 2},
        {"name": "Biotechnology — Principles & Processes", "priority_weight": 4},
        {"name": "Biotechnology & its Applications", "priority_weight": 3},
        {"name": "Organisms & Populations", "priority_weight": 2},
        {"name": "Ecosystem", "priority_weight": 3},
        {"name": "Biodiversity & Conservation", "priority_weight": 2},
        {"name": "Environmental Issues", "priority_weight": 2},
    ],
    "Zoology": [
        {"name": "Animal Kingdom", "priority_weight": 3},
        {"name": "Structural Organisation in Animals", "priority_weight": 2},
        {"name": "Biomolecules", "priority_weight": 3},
        {"name": "Digestion & Absorption", "priority_weight": 3},
        {"name": "Breathing & Exchange of Gases", "priority_weight": 3},
        {"name": "Body Fluids & Circulation", "priority_weight": 3},
        {"name": "Excretory Products & their Elimination", "priority_weight": 3},
        {"name": "Locomotion & Movement", "priority_weight": 2},
        {"name": "Neural Control & Coordination", "priority_weight": 4},
        {"name": "Chemical Coordination & Integration", "priority_weight": 4},
        {"name": "Human Reproduction", "priority_weight": 5},
        {"name": "Reproductive Health", "priority_weight": 3},
        {"name": "Human Health & Disease", "priority_weight": 4},
    ],
}

NDA_SYLLABUS = {
    "Mathematics": [
        {"name": "Algebra (Set Theory & Complex Numbers)", "priority_weight": 4},
        {"name": "Matrices & Determinants", "priority_weight": 4},
        {"name": "Quadratic Equations", "priority_weight": 3},
        {"name": "Sequences & Series", "priority_weight": 3},
        {"name": "Permutations & Combinations", "priority_weight": 3},
        {"name": "Binomial Theorem", "priority_weight": 2},
        {"name": "Logarithms", "priority_weight": 2},
        {"name": "Trigonometry", "priority_weight": 5},
        {"name": "Inverse Trigonometric Functions", "priority_weight": 2},
        {"name": "Properties of Triangles & Heights & Distances", "priority_weight": 3},
        {"name": "Analytical Geometry (2D)", "priority_weight": 4},
        {"name": "Analytical Geometry (3D)", "priority_weight": 3},
        {"name": "Vector Algebra", "priority_weight": 3},
        {"name": "Differential Calculus", "priority_weight": 5},
        {"name": "Integral Calculus & Differential Equations", "priority_weight": 5},
        {"name": "Probability", "priority_weight": 3},
        {"name": "Statistics", "priority_weight": 3},
    ],
    "English (GAT)": [
        {"name": "Vocabulary (Synonyms & Antonyms)", "priority_weight": 3},
        {"name": "Spotting Errors & Grammar", "priority_weight": 4},
        {"name": "Sentence Improvement", "priority_weight": 3},
        {"name": "Reading Comprehension", "priority_weight": 4},
        {"name": "Cloze Test", "priority_weight": 2},
        {"name": "Idioms & Phrases", "priority_weight": 2},
        {"name": "Ordering of Sentences", "priority_weight": 2},
    ],
    "General Knowledge (GAT)": [
        {"name": "Physics", "priority_weight": 4},
        {"name": "Chemistry", "priority_weight": 3},
        {"name": "General Science (Biology, Health)", "priority_weight": 3},
        {"name": "Indian History & Freedom Movement", "priority_weight": 4},
        {"name": "Indian Geography", "priority_weight": 3},
        {"name": "World Geography", "priority_weight": 2},
        {"name": "Indian Polity & Constitution", "priority_weight": 3},
        {"name": "Indian Economy", "priority_weight": 3},
        {"name": "Current Affairs & Static GK", "priority_weight": 4},
        {"name": "Defence-related Awareness", "priority_weight": 3},
    ],
}

BOARDS_SYLLABUS = {
    "Physics": [
        {"name": "Electric Charges & Fields", "priority_weight": 4},
        {"name": "Electrostatic Potential & Capacitance", "priority_weight": 4},
        {"name": "Current Electricity", "priority_weight": 5},
        {"name": "Moving Charges & Magnetism", "priority_weight": 4},
        {"name": "Magnetism & Matter", "priority_weight": 3},
        {"name": "Electromagnetic Induction", "priority_weight": 4},
        {"name": "Alternating Current", "priority_weight": 3},
        {"name": "Electromagnetic Waves", "priority_weight": 2},
        {"name": "Ray Optics & Optical Instruments", "priority_weight": 4},
        {"name": "Wave Optics", "priority_weight": 3},
        {"name": "Dual Nature of Radiation & Matter", "priority_weight": 3},
        {"name": "Atoms", "priority_weight": 2},
        {"name": "Nuclei", "priority_weight": 3},
        {"name": "Semiconductor Electronics", "priority_weight": 3},
    ],
    "Chemistry": [
        {"name": "Solutions", "priority_weight": 4},
        {"name": "Electrochemistry", "priority_weight": 4},
        {"name": "Chemical Kinetics", "priority_weight": 4},
        {"name": "d & f-Block Elements", "priority_weight": 4},
        {"name": "Coordination Compounds", "priority_weight": 4},
        {"name": "Haloalkanes & Haloarenes", "priority_weight": 3},
        {"name": "Alcohols, Phenols & Ethers", "priority_weight": 3},
        {"name": "Aldehydes, Ketones & Carboxylic Acids", "priority_weight": 4},
        {"name": "Amines", "priority_weight": 3},
        {"name": "Biomolecules", "priority_weight": 3},
    ],
    "Mathematics": [
        {"name": "Relations & Functions", "priority_weight": 3},
        {"name": "Inverse Trigonometric Functions", "priority_weight": 2},
        {"name": "Matrices", "priority_weight": 3},
        {"name": "Determinants", "priority_weight": 3},
        {"name": "Continuity & Differentiability", "priority_weight": 4},
        {"name": "Applications of Derivatives", "priority_weight": 4},
        {"name": "Integrals", "priority_weight": 5},
        {"name": "Applications of Integrals", "priority_weight": 3},
        {"name": "Differential Equations", "priority_weight": 3},
        {"name": "Vector Algebra", "priority_weight": 3},
        {"name": "Three-Dimensional Geometry", "priority_weight": 4},
        {"name": "Linear Programming", "priority_weight": 2},
        {"name": "Probability", "priority_weight": 4},
    ],
    "Biology": [
        {"name": "Sexual Reproduction in Flowering Plants", "priority_weight": 4},
        {"name": "Human Reproduction", "priority_weight": 5},
        {"name": "Reproductive Health", "priority_weight": 3},
        {"name": "Principles of Inheritance & Variation", "priority_weight": 5},
        {"name": "Molecular Basis of Inheritance", "priority_weight": 5},
        {"name": "Evolution", "priority_weight": 3},
        {"name": "Human Health & Disease", "priority_weight": 4},
        {"name": "Microbes in Human Welfare", "priority_weight": 2},
        {"name": "Biotechnology — Principles & Processes", "priority_weight": 4},
        {"name": "Biotechnology & its Applications", "priority_weight": 3},
        {"name": "Organisms & Populations", "priority_weight": 2},
        {"name": "Ecosystem", "priority_weight": 3},
        {"name": "Biodiversity & Conservation", "priority_weight": 2},
    ],
    "English": [
        {"name": "Reading Comprehension (Unseen Passage)", "priority_weight": 4},
        {"name": "Note Making & Summarising", "priority_weight": 2},
        {"name": "Notice / Invitation / Advertisement Writing", "priority_weight": 3},
        {"name": "Letter Writing (Formal / Business)", "priority_weight": 3},
        {"name": "Article / Report Writing", "priority_weight": 3},
        {"name": "Flamingo — Prose", "priority_weight": 4},
        {"name": "Flamingo — Poetry", "priority_weight": 3},
        {"name": "Vistas — Supplementary Reader", "priority_weight": 3},
    ],
    "Accountancy": [
        {"name": "Accounting for Not-for-Profit Organisations", "priority_weight": 3},
        {"name": "Accounting for Partnership Firms — Fundamentals", "priority_weight": 4},
        {"name": "Reconstitution of Partnership (Admission)", "priority_weight": 4},
        {"name": "Reconstitution of Partnership (Retirement / Death)", "priority_weight": 3},
        {"name": "Dissolution of Partnership Firm", "priority_weight": 3},
        {"name": "Accounting for Share Capital", "priority_weight": 4},
        {"name": "Accounting for Debentures", "priority_weight": 3},
        {"name": "Analysis of Financial Statements", "priority_weight": 3},
        {"name": "Cash Flow Statement", "priority_weight": 3},
    ],
    "Business Studies": [
        {"name": "Nature & Significance of Management", "priority_weight": 3},
        {"name": "Principles of Management", "priority_weight": 3},
        {"name": "Business Environment", "priority_weight": 2},
        {"name": "Planning", "priority_weight": 3},
        {"name": "Organising", "priority_weight": 3},
        {"name": "Staffing", "priority_weight": 3},
        {"name": "Directing", "priority_weight": 3},
        {"name": "Controlling", "priority_weight": 2},
        {"name": "Financial Management", "priority_weight": 4},
        {"name": "Financial Markets", "priority_weight": 3},
        {"name": "Marketing Management", "priority_weight": 4},
        {"name": "Consumer Protection", "priority_weight": 2},
    ],
    "Economics": [
        {"name": "Introduction to Microeconomics", "priority_weight": 2},
        {"name": "Consumer Equilibrium & Demand", "priority_weight": 4},
        {"name": "Producer Behaviour & Supply", "priority_weight": 4},
        {"name": "Forms of Market & Price Determination", "priority_weight": 3},
        {"name": "National Income & Related Aggregates", "priority_weight": 4},
        {"name": "Money & Banking", "priority_weight": 3},
        {"name": "Determination of Income & Employment", "priority_weight": 3},
        {"name": "Government Budget & the Economy", "priority_weight": 3},
        {"name": "Balance of Payments", "priority_weight": 2},
    ],
}

COURSES = ["JEE", "NEET", "NDA", "Boards"]

COURSE_SYLLABI = {
    "JEE": JEE_SYLLABUS,
    "NEET": NEET_SYLLABUS,
    "NDA": NDA_SYLLABUS,
    "Boards": BOARDS_SYLLABUS,
}
