"""JEE curated syllabus. NEET/NDA/Boards intentionally empty for v1."""

JEE_SYLLABUS = {
    "Physics": [
        {"name": "Kinematics", "priority_weight": 3},
        {"name": "Laws of Motion", "priority_weight": 3},
        {"name": "Work, Power & Energy", "priority_weight": 3},
        {"name": "Rotational Motion", "priority_weight": 4},
        {"name": "Gravitation", "priority_weight": 2},
        {"name": "Properties of Solids & Liquids", "priority_weight": 2},
        {"name": "Thermodynamics", "priority_weight": 4},
        {"name": "Kinetic Theory of Gases", "priority_weight": 2},
        {"name": "Oscillations & Waves", "priority_weight": 4},
        {"name": "Ray Optics", "priority_weight": 3},
        {"name": "Wave Optics", "priority_weight": 3},
        {"name": "Electrostatics", "priority_weight": 5},
        {"name": "Current Electricity", "priority_weight": 5},
        {"name": "Magnetic Effects of Current & Magnetism", "priority_weight": 4},
        {"name": "Electromagnetic Induction & AC", "priority_weight": 4},
        {"name": "Electromagnetic Waves", "priority_weight": 2},
        {"name": "Dual Nature of Matter & Radiation", "priority_weight": 3},
        {"name": "Atoms & Nuclei", "priority_weight": 3},
        {"name": "Semiconductor Electronics", "priority_weight": 3},
    ],
    "Chemistry": [
        {"name": "Some Basic Concepts of Chemistry (Mole)", "priority_weight": 4},
        {"name": "Atomic Structure", "priority_weight": 3},
        {"name": "Chemical Bonding & Molecular Structure", "priority_weight": 5},
        {"name": "States of Matter (Gases & Liquids)", "priority_weight": 2},
        {"name": "Thermodynamics & Thermochemistry", "priority_weight": 4},
        {"name": "Solutions", "priority_weight": 3},
        {"name": "Equilibrium (Ionic & Chemical)", "priority_weight": 4},
        {"name": "Redox & Electrochemistry", "priority_weight": 4},
        {"name": "Chemical Kinetics", "priority_weight": 3},
        {"name": "Surface Chemistry", "priority_weight": 2},
        {"name": "Periodic Table & Periodicity", "priority_weight": 3},
        {"name": "s-Block Elements", "priority_weight": 2},
        {"name": "p-Block Elements", "priority_weight": 4},
        {"name": "d & f Block Elements", "priority_weight": 3},
        {"name": "Coordination Compounds", "priority_weight": 4},
        {"name": "General Organic Chemistry (GOC)", "priority_weight": 5},
        {"name": "Hydrocarbons", "priority_weight": 3},
        {"name": "Haloalkanes & Haloarenes", "priority_weight": 3},
        {"name": "Alcohols, Phenols & Ethers", "priority_weight": 3},
        {"name": "Aldehydes, Ketones & Carboxylic Acids", "priority_weight": 4},
        {"name": "Amines & Diazonium Salts", "priority_weight": 3},
        {"name": "Biomolecules & Polymers", "priority_weight": 2},
    ],
    "Mathematics": [
        {"name": "Sets, Relations & Functions", "priority_weight": 3},
        {"name": "Complex Numbers", "priority_weight": 3},
        {"name": "Quadratic Equations", "priority_weight": 3},
        {"name": "Matrices & Determinants", "priority_weight": 4},
        {"name": "Permutations & Combinations", "priority_weight": 3},
        {"name": "Binomial Theorem", "priority_weight": 3},
        {"name": "Sequences & Series", "priority_weight": 3},
        {"name": "Limits, Continuity & Differentiability", "priority_weight": 5},
        {"name": "Differentiation & Applications of Derivatives", "priority_weight": 5},
        {"name": "Integrals & Applications", "priority_weight": 5},
        {"name": "Differential Equations", "priority_weight": 3},
        {"name": "Straight Lines", "priority_weight": 3},
        {"name": "Circles", "priority_weight": 3},
        {"name": "Conic Sections (Parabola, Ellipse, Hyperbola)", "priority_weight": 4},
        {"name": "Three Dimensional Geometry", "priority_weight": 4},
        {"name": "Vector Algebra", "priority_weight": 4},
        {"name": "Probability", "priority_weight": 4},
        {"name": "Statistics", "priority_weight": 2},
        {"name": "Trigonometric Functions & Equations", "priority_weight": 3},
        {"name": "Inverse Trigonometric Functions", "priority_weight": 2},
        {"name": "Mathematical Reasoning", "priority_weight": 1},
    ],
}

COURSES = ["JEE", "NEET", "NDA", "Boards"]

# NEET / NDA / Boards remain empty containers per v1 scope
COURSE_SYLLABI = {
    "JEE": JEE_SYLLABUS,
    "NEET": {},
    "NDA": {},
    "Boards": {},
}
